apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc
  namespace: jelly
  labels:
    app: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jellyseerr-pv
  resources:
    requests:
      storage: 3Gi