apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-config
  namespace: arr-stack
  labels:
    app: cleanuparr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synostorage
  resources:
    requests:
      storage: 1Gi