apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-config
  namespace: arr-stack
  labels:
    app: huntarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synostorage
  resources:
    requests:
      storage: 2Gi