apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik-database
  namespace: default
spec:
  name: authentik
  owner: authentik_user
  cluster:
    name: database
  databaseReclaimPolicy: retain
