---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-user-secret
  namespace: default
spec:
  encryptedData:
    password: AgBWHr7z6ZlHAfjNQqbCPF1E8RHv8BerTbOhBK3OPJ0j8cYuWbalaAFn5vMmVAakv02GXTyLAoxuj9VYVDEuu2W02DXn35JL62ssjf6end6XjpMWLEF/w+GkIw6styPNO6izF0goPhP+V+OGUqvzDUmQgAasQg/OIynA6/3iCbK6Eq7VP8qR+lhAQsp76HPpQlaNU1ge3VY86dXxKkFr22ILaagoUmuAast3VNWi5MP7bOerwarbtDOlRmfj7+GXeUW2z3gc21WHJ+N6dZv+acRZmrvUE9gKEl35SXGLPDRX21zJCnjoCGLJx3q5XQL884UoXzew+EjOO8ThZt99ymJp/LeGBnFj0z/O7Bipwc5gd1aS0EGGePhTjo1vsEbocGhBzdfelw7vTAwk4Ud8PZzbznJxuVBioJ0L/7/vQ37wsXif0jQk2UxHkwhRxKkjpjodQ3br/IxCheKwv1LjPGOIvTFIAl5a+snEAurIDEqjY875x47hmfoyW+Btt871PBvUWk3ep9F0A/03ZLd0QmK8W8aVtM4/GuXVFkOX127YzOeA6MlvvsP52LTzPYUC7taNdfBMcPB/+f2r5s5xDRO6Xx66OhAbnOxYs8uFZs/mfBn7zxMFLUBfRmq7JYioYMEaI/ZENAebbDLwx9XY6OeUacIcsmDMn5ZVWDCBDiX3MERzzoAdvnNhSYQ6H8eYa+btvCUpoVhp0Q==
    username: AgCLIo+Ra52+qmjpVdoDULIaW7j9uqRqN4adfS/VWIBKE1iMY7+9m+KIfT/uq6u3sh7f99ERIj6XZMi6IdQuTKgdeCuT0Xqv+NLpZtkDUOLOJH6L5a3afPRMMNdoYMzvQnICZZMWEsi3+Niks1PkiEqMA7aw9A8arucCkM7yUV6d2aABrZqsejFF8DO8TYWWmPd803WEne5CVhSteo0ww53OMgfTImm0sWoHITAu0eo4aIzOge9EU9Knzn5QZeVoeQB/C2tYhTJXJ04GXr+wLArJgyk55hbcy5Cd7I2mloZn//51X6S4XggQGpqUyLxl70egsKP4bOmrPUcmdZbyJofwc5aIGpoKn6KO+lDwWETK0m/Ck04GhXj5RCoBU+YT22korA8UIAuZr1hJMSprPR5TdpanxWoP/piZ+H4lYdk1MEK4lBxU9X/IwEothVe5HbgBTp+wCI19HPewu0E4F5ayicuG7y4mtw58N91WsJgXXfw7xAxRdd1V/2WZfSEtWmu0nfbyA28LP6lZgQ9ETVF1rnG+/cKyd1SLp7FSkFF//RU7Ur9HvDuy5V3dVHUA4Xy6hJJ4QtilTMuYfIFb+oERJ1a+dY4X8kIQPqndc6DVnBo1r4WLDe1o1IF/ohJrawJIEx3ZhrBCIfdDIvcmgniWiaSbOHExZyKlFy6HBx2OaRQEg9mLpQOaKE5yqUVU1f0tVYm355PNJzeLRvQbyg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: authentik-user-secret
      namespace: default
    type: kubernetes.io/basic-auth
