---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-user-secret
  namespace: default
spec:
  encryptedData:
    password: AgAPQKu8l/VaB1zS8aGwduPSIOPFCWOXfZW02iCyvfwRaNbOPaSswo6eT40/yZLTJP7tinxilPsqWPCLTP0rSspX+fy3kx+PZsUvjAtJHg9zsdZ4bRMqY39IZe/eJHhDF1M7qrMzfTy6IXdW9U2tTfsElsS4og5iV44bf6Z1DoFbEAKsLwjJ/OWsPkFKynB/2VuQwseTD8U5A8DYkj7Lkl3f0g3CwIP63S1RKIMNlTTZ0YrKZx8BhkWPQVHF7AxwupsNG6YKqLhsIcS/F4BNTdzo6La0A+1GpPU7dzSyL5wYyiwruXo3oYUpaPhBS5tvESDbejEE9zSdCF3e/5VOyjCeJnrGhK2NPN0d0Eu/w7vfAGKF8+f3bjYLl66ltE1NV2fJyZFsA/J6yyb+iZpSduOT05wZ2MMaDb7PWH7hkRcSGyw+I+L4LJqSoGqO3gtAkm5wMoPVOGyAzmgUkvYN+Pb97hCZj0oZY0KKKQG/97CKmXT/2+s4wqbJV6ID88lSG+jMdnlRq5ObfIIGg3UN8IkGH1F0MBnK1kv0RGE5DTGUQmRQ/OIYfe2q7+TAjqXCj6y8LN3JJ54xsEK0MdRz800e/yFB0QgOH+xtNXFeKJQg7JCBMvoa2t0wYNRrbyIe0yRpomPI53dNuP5pXX4jg5VwErxHfUidJF8RM7EO6Rp3qs/Ri1zJzfnJcwtVsZvR9dt8VXC9FdPng2N/noNWUjRayDoTmmGE4pRKOKIYAgykLcdgdHHXjIVzYy02og==
    username: AgBEiGajqLJk6lRxflcRdgnpMhbsQtWk8ZA5wtwgD+VO2wiMD9/dVyF520PP8faCV/hrnE0FOFqab2d/f31k1aJvRZp6IPbCTl17gnUo3HFlzdgwmca4dvBzSy2+VdKXvXm3OJ4qhAi0w6PgApFl1BZx6yiJUH8LmBuCR+ke73+c/dAEakqh9vNsMrIpMcw2oEMl4zgmVRTDqZ9T/2bu6WpKcDfL/VaXSN/bfZDdpiLpTnToCwrZg1+qOZ2XO9mR5PzswQPfcbPf818G21/O2IiARRBf5uW5mjFDWWu1SKibh65rBcPgjU5D+T4WlUrKm0Vmsagg1IgDGm+Zn/IGLzN/wnwkDH4FB/iiEDnQhucnmjVZIjcAhqkZtXSyvUjJR/Wu2P0HVe7Cq7xR3nHCJ+BZNlQabWdmodP+FG+d/vkJKLyI2keY+n0MiM5Ga51g8ZnPKyW9apL03OJ0GCdXnlDIaHSpaCeTzt/yp2NmCXGNIlMGJaYXeyNLIja9LE090807Tje7I2yq9vJIuyoYfLXST/OqOIOko6FmXB0DC5R/nuyQFqlStWV7TfYswTZbTGSML5vNhqPPvB48nRIX7cGitd3iJO1fhYm4t/d//Z6pEcf8H8SOmOdRMR6G/qZQSvdSVZ7usXvDMtG/X64CZyMYMbbBUhdmNE/T0Dk0H0nw/Kha95UE5dAiOyRk4SZBzhqAGOTtmCIjng==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: n8n-user-secret
      namespace: default
    type: kubernetes.io/basic-auth