apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-user-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgAcKv+zbycb6dviIfiayfe6lOSaU9BbGbHL6VlHVHy9dze5Smieq+1q084utIfd5ciJ0cl1sf77k54ZRkU69TtF6XyZTlKPN1W2/knfLPCR1esLlqpup9zRqqWS4R20bJ4zjbaINlW6Uk1A2txuNM02uufVvlRmhA8ostmEgeTGVKJRGw70UMeHmmDDcfwhuz4I+zl6hbjAYLNB2WgSlmUTu7EAcQQqgapQBrh0w/TbdKoUSPjsGfoNbDyGMm28Ii1v5KZiFz0mikia8poJ3Spu9Y/jdugmZ5qY6K2XdocqXLpwsdt9Tx4dvWERWNe2vW9k6JeVTUOB7G5GB0TjOVpRrDPia4q9Qv2XCHNTNMABYwS9S+D62x6goc4TG578xiAni0l6UibauACWc2l3PrDOreaaVLcusB1DqjY31jBYRAoNxsuGuF3BRKqB0ErmbWlvDkGtaZUh5bMCQyvMz6PTsFbmbIhV56iOsyDIU6n6y2W923kQf/C4u+woSgZuQIFPWbHol5we2j0m/tY0eIf/BaB7XQkqLDLZD43lcEhlnSpuVLPwGykGIHcaiqHm9uoyitc8+L9jbv36UOETD5648l/J+pQNKbpxaC83QtTtyat+MWOhqwnQYAaFdCYhu1sbaGO+TIw0OZexn8RGQRrvzNJcYQKj8wed6uIAoyypxL6QZ8Rya3d7Fl2cJO+U1QLzqGsKZmleiKcRdmBKdkd8tT+nxRTVUCM4m63ssf1M8qyHf+uw+C964w3oSw==
    username: AgCfGedYtu1SHer+O7SVV64POjIcfIUmRquGrChjbfTAwKd5aQRiMCCXU2Vk5cq/ko1WzhnjQsbD20ZwYq4jjO755PgMRTJzlUlbJYiFUxnsPO5mcFvpD1zMxVvFF81ul2W4oIyvHZQmAtO9h72ckuITK6f2P5JfNF84SVBdwYoc8B41K47ZNqFPLD3bGo9gZKEWJLpngP0fkRj9Wx8qGD2f2eBChcK1HKtW0IteqJJAOpWnhd1GRD30Cr+AQdKDuRKwCU1Q7CKa/6GiRbnO19tQySl+43/hZkKUCv50ppM3hvQbfAIkrNVTbZLDbMtFGy4iIUXjgAaFLgLs/mhShv1dkXjG1YKEd+nFDKvs9FjsoCyt6xBx8ch5Da3GKwF8eXnfUQYPv8+757RaatcYfDxKPgg5BM+N9VlKQzLu2enEu6mrsNsmIZ0im/ARjwXLEjZ+yunqreZCqsIEXJQ4+5HJ0+CFRqOoe4JoqUlOrO9s2nKMNyr9SFUcA+OHmGX3k3GACS6d2NtM5mESYjeOXtCGuQVbAznGU/AEiLLEngIXn6HcojZk00Y2FN0XerWjHGKXkXcN5usyCQBSxtMr6eORLuYpRLGDYo75Y/PPAr1upUMpPmgcE+yE/9sOBaZ9MdyAzmlw9z57HNwebTPat4vfa3qAOy5/qcM42HudC2htU0hbItGUfVFMjmzhDETr+EuzQDL3MDze3Q==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: n8n-user-secret
      namespace: n8n
    type: kubernetes.io/basic-auth
