---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: misc
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCFlJWxIBf2EIIOG9b+Dkyp3FYwmWCMWqghvZtaPNoQrtX1/ustr4JMu60Dkxj/zCMq7uwQwUhoMvlEJ3j4iPbIjOvGCR5qYv7+xz1F3XO/m/KyvlHPege1cqddzxhhiVHJ9Lu4DDWbH5eSFMcqgmRqExmyuKyfNu1IgjqCOVyLy/D5Bb+g8D9EI5wEBtO6C5bbk89p9aOtE4x6vF5yRg3r0RDKVLjCLUZc9d5fCsy4AxDhD3hDD51/ypJjKoxO6RUIG9C3RQ2eSzrNhmPtoQuoWCDv6lygKdIKQNsja/QRPTvUo8C2us3+wAi0A/Zha0Z+DalxCrLgNuSfxkZyUewcC3SvrXE052WNRaqImtHJGhsLiZSZbSQoU7A6+01AaksrcOqrxg9iXCl2MpRaEXOy4eVdB4j5jRIZ+fjLJ2MB7Qz6SbYQUR1N4L46zLhDXyNGA3JAoubuM0e/xPP9MZmJgDRI7BGLHgs/0c9rjNpoCtzJ38AUIb5AbKj3S6wIkv1C25td1hPUdt38mNIQGMVkvoyluMvdLPiJsA9F5od4BmsJ51jtRqdMd7Zspr7SqjWZEHGSybyajn5xDy4XAhbWDyG4HqGN4h6oQ8qvSpDT4FP3ktB3OOVL7gUANBf+YQkiPLGSChGRLihRP4ZvF/rU6yL6WGdBse8jXp/kHw2l9EFsKE9Al6nSDmpgeoh5bZlUTR2wEUhlVg==
  template:
    metadata:
      name: pihole-password
      namespace: misc
    type: Opaque